apiVersion: apps/v1
kind: Deployment
metadata:
  name: exam2025-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: exam2025
  template:
    metadata:
      labels:
        app: exam2025
    spec:
      containers:
      - name: exam2025
        image: gcr.io/examen-458207/exam2025:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
          - name: GCP_BUCKET_NAME
            value: "REPLACE_BUCKET_NAME"
        livenessProbe:
          periodSeconds: 2
          httpGet:
            path: /probe
            port: 5000


